// <auto-generated />
namespace WebScrapingService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class OverallStatisticsColumnChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverallStatisticsColumnChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202003280823498_OverallStatisticsColumnChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
